### ISSUE TITLE
[BUG] Do not count /healthz against the api rate limit.

### ISSUE THREAD

**Issue by ikuradon** [Cameri/nostream#182]
**Describe the bug**

In kubernetes, healthcheck(livenessProbe, startupProbe) access come from semi-fixed in-cluster ip address. And check occurs every 10 seconds by default (= 360 times per hour), the API limitation on the nostream side will be hit and EOF will be returned, resulting in repeated restarts (CrashLoopbackOff).

**To Reproduce**
1. Deploy nostream to kubernetes with livenessProbe config
```yaml
ports:
  - name: http
    containerPort: 8008
    protocol: TCP
livenessProbe:
  httpGet:
    path: /healthz
    port: http
```
3. wait about an hour.

**Expected behavior**

healthcheck succeeds without problems and the pod continues to run normally.

**System (please complete the following information):**
 - OS: Ubuntu 22.04, RKE2 v1.26.1+rke2r1
 - Platform: kubernetes
 - Version: 1.22.1
